/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolishRouteImport } from './routes/polish'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BankRouteImport } from './routes/bank'
import { Route as IndexRouteImport } from './routes/index'

const PolishRoute = PolishRouteImport.update({
  id: '/polish',
  path: '/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/builder': typeof BuilderRoute
  '/exams': typeof ExamsRoute
  '/polish': typeof PolishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/builder': typeof BuilderRoute
  '/exams': typeof ExamsRoute
  '/polish': typeof PolishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/builder': typeof BuilderRoute
  '/exams': typeof ExamsRoute
  '/polish': typeof PolishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bank' | '/builder' | '/exams' | '/polish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bank' | '/builder' | '/exams' | '/polish'
  id: '__root__' | '/' | '/bank' | '/builder' | '/exams' | '/polish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  BuilderRoute: typeof BuilderRoute
  ExamsRoute: typeof ExamsRoute
  PolishRoute: typeof PolishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polish': {
      id: '/polish'
      path: '/polish'
      fullPath: '/polish'
      preLoaderRoute: typeof PolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  BuilderRoute: BuilderRoute,
  ExamsRoute: ExamsRoute,
  PolishRoute: PolishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
